apiVersion: v1
kind: Pod
metadata:
  name: webapp-release-0-5
  labels:
    app: webapp
    release: "0-5" 
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release-0-5

---   
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
     
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release0



--- 
apiVersion: v1

kind: Service
metadata:
  name: fleetman-queue

spec:

  selector:
    app: queue

  ports:
  - name: http
    port: 8161
    nodePort: 30010

  type: NodePort